### ISSUE TITLE
Add rwd-checksum tool and rwd-write tool

### ISSUE THREAD

**Issue by slovak194** [gregjhogan/rwd-xray#3]
Hi, gregjhogan!

I did some development on my [fork](https://github.com/slovak194/rwd-xray) which can be useful for the following workflows:
1. You did some changes to unpacked binary and want to pack it back into rwd with proper encryption, checksums, etc.
2. You are going to make changes to rwd file directly without unpacking it. Ones you are done - you can calculate file checksum and write it to the end. Not sure if it will work with flashing tool, I'll check soon.

Please, let me know if such contribution is welcome and I'll update readme and prepare pull request.

Best regards!

**Comment by gregjhogan** [comment]
yeah, submit a PR if you have something good.  thanks!

**Comment by slovak194** [comment]
What about migration to python3?

**Comment by gregjhogan** [comment]
Yeah, I want to support 2 and 3.  Tried to not do anything that would break in 3 but recently noticed some things are broken.

**Comment by slovak194** [comment]
Hi! Did you have a chance to try and flash a car with a modified rwd file? I'm having hard time making a Honda j2534 software tool to think there is a firmware update for a module. Can we share our experiense by mail messanger?

**Comment by energee** [comment]
@slovak194 I think you can write this to ECU with ISO 14229.

**Comment by gregjhogan** [comment]
@slovak194 I wrote something that [scans for checksums](https://github.com/gregjhogan/rwd-xray/blob/master/tools/checksum-search.py) and [builds rwd files](https://github.com/gregjhogan/rwd-xray/blob/master/tools/rwd-builder.py)

Currently the builder requires that you already constructed the firmware you want to flash (including checksums inside the firmware) since I haven't found a reliable way to generalize finding and updating checksums.

Also, note that rwd files are partial firmware updates, but the builder can handle starting from the full firmware (since that is the most likely starting point).

If you want to flash an RWD file over CAN (not LIN), you can use something new I wrote: https://autoecu.io/
